services:
  backend:
    build: ./BE
    container_name: live-backend
    expose:
      - "3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=7d
      - REFRESH_TTL_SEC=604800
    restart: always

  frontend:
    build: ./FE
    container_name: live-frontend
    expose:
      - "80"
    depends_on:
      - backend
    restart: always

  reverse-proxy:
    image: nginx:alpine
    container_name: live-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./reverse-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend
    restart: always
