name: Deploy to VM

on:
  push:
    branches:
      - release # 🚀 only trigger on release branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/L.I.V.E-FE
            git pull origin release
            docker compose down
            docker compose up -d --build
