name: Deploy Backend

on:
  push:
    branches: [ "release" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build backend Docker image
      run: docker build -t live-backend ./BE

    - name: Save Docker image
      run: docker save live-backend | gzip > live-backend.tar.gz

    - name: Copy image to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.AZURE_HOST }}
        username: ${{ secrets.AZURE_USER }}
        key: ${{ secrets.AZURE_SSH_KEY }}
        source: "live-backend.tar.gz"
        target: "~/"

    - name: Load image & restart container on server
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.AZURE_HOST }}
        username: ${{ secrets.AZURE_USER }}
        key: ${{ secrets.AZURE_SSH_KEY }}
        script: |
          docker load < ~/live-backend.tar.gz
          cd ~/L.I.V.E-FE
          docker compose up -d backend
